//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGeneratorSQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoGeneratorSQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.txt.
        /// </summary>
        internal static string PathToCities {
            get {
                return ResourceManager.GetString("PathToCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.txt.
        /// </summary>
        internal static string PathToCompanies {
            get {
                return ResourceManager.GetString("PathToCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.txt.
        /// </summary>
        internal static string PathToCountries {
            get {
                return ResourceManager.GetString("PathToCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.txt.
        /// </summary>
        internal static string PathToNames {
            get {
                return ResourceManager.GetString("PathToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.txt.
        /// </summary>
        internal static string PathToOperator {
            get {
                return ResourceManager.GetString("PathToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperatorCode.txt.
        /// </summary>
        internal static string PathToOperatorCode {
            get {
                return ResourceManager.GetString("PathToOperatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.txt.
        /// </summary>
        internal static string PathToPosition {
            get {
                return ResourceManager.GetString("PathToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sename.txt.
        /// </summary>
        internal static string PathToSenames {
            get {
                return ResourceManager.GetString("PathToSenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.txt.
        /// </summary>
        internal static string PathToStreets {
            get {
                return ResourceManager.GetString("PathToStreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string SplitterRuleChar {
            get {
                return ResourceManager.GetString("SplitterRuleChar", resourceCulture);
            }
        }
    }
}
