//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoGeneratorSQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoGeneratorSQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomSyntaxes.txt.
        /// </summary>
        internal static string CustomSyntaxesPath {
            get {
                return ResourceManager.GetString("CustomSyntaxesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FillYourCustomFile.
        /// </summary>
        internal static string CustonFileEmptyException {
            get {
                return ResourceManager.GetString("CustonFileEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name must be: 1)Not less than 3 letters 2)Only letters.
        /// </summary>
        internal static string ExceptionNameRule {
            get {
                return ResourceManager.GetString("ExceptionNameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string Formatter {
            get {
                return ResourceManager.GetString("Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValueException {
            get {
                return ResourceManager.GetString("InvalidValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.txt.
        /// </summary>
        internal static string PathToCities {
            get {
                return ResourceManager.GetString("PathToCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.txt.
        /// </summary>
        internal static string PathToCompanies {
            get {
                return ResourceManager.GetString("PathToCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.txt.
        /// </summary>
        internal static string PathToCountries {
            get {
                return ResourceManager.GetString("PathToCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string PathToCustomDir {
            get {
                return ResourceManager.GetString("PathToCustomDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        internal static string PathToDirBasic {
            get {
                return ResourceManager.GetString("PathToDirBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string PathToDirLog {
            get {
                return ResourceManager.GetString("PathToDirLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs\Log.txt.
        /// </summary>
        internal static string PathToFileWithLog {
            get {
                return ResourceManager.GetString("PathToFileWithLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.txt.
        /// </summary>
        internal static string PathToNames {
            get {
                return ResourceManager.GetString("PathToNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.txt.
        /// </summary>
        internal static string PathToOperator {
            get {
                return ResourceManager.GetString("PathToOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.txt.
        /// </summary>
        internal static string PathToOperatorCode {
            get {
                return ResourceManager.GetString("PathToOperatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.txt.
        /// </summary>
        internal static string PathToPosition {
            get {
                return ResourceManager.GetString("PathToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sename.txt.
        /// </summary>
        internal static string PathToSenames {
            get {
                return ResourceManager.GetString("PathToSenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.txt.
        /// </summary>
        internal static string PathToStreets {
            get {
                return ResourceManager.GetString("PathToStreets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomSyntax.
        /// </summary>
        internal static string PathToSyntax {
            get {
                return ResourceManager.GetString("PathToSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters.
        /// </summary>
        internal static string RuleAllLettersException {
            get {
                return ResourceManager.GetString("RuleAllLettersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string RuleLessThanException {
            get {
                return ResourceManager.GetString("RuleLessThanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need more than.
        /// </summary>
        internal static string RuleMoreThanException {
            get {
                return ResourceManager.GetString("RuleMoreThanException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not repeated.
        /// </summary>
        internal static string RuleNotRepeatedException {
            get {
                return ResourceManager.GetString("RuleNotRepeatedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string SplitterRuleChar {
            get {
                return ResourceManager.GetString("SplitterRuleChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string StateEnable {
            get {
                return ResourceManager.GetString("StateEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating...
        /// </summary>
        internal static string StateGenerating {
            get {
                return ResourceManager.GetString("StateGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string StateOff {
            get {
                return ResourceManager.GetString("StateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string StateOn {
            get {
                return ResourceManager.GetString("StateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On waiting...
        /// </summary>
        internal static string StateoOnWaiting {
            get {
                return ResourceManager.GetString("StateoOnWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string TimerStopped {
            get {
                return ResourceManager.GetString("TimerStopped", resourceCulture);
            }
        }
    }
}
